parameters:
  env(SR_TENANT_DEFAULT): 'default'
services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Interfacing\ProviderInterface\InterfaceScreenProviderInterface:
      tags: ['interfacing.screen_provider']

