# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/'

  App\Service\Interfacing\Registry\ScreenCatalog: ~
  App\Service\Interfacing\Registry\ActionCatalog: ~
  App\Service\Interfacing\Runtime\ActionRunner: ~
