services:
  SmartResponsor\Interfacing\Service\Interfacing\Query\HttpBillingMeterQueryService:
    arguments:
      $client: '@http_client'
      $baseUrl: '%env(string:SR_BILLING_API_BASE)%'
      $path: '%env(default::SR_BILLING_API_METER_PATH)%'
    tags: ['interfacing.query']

  SmartResponsor\Interfacing\Service\Interfacing\Query\HttpOrderSummaryQueryService:
    arguments:
      $client: '@http_client'
      $baseUrl: '%env(string:SR_ORDER_API_BASE)%'
      $path: '%env(default::SR_ORDER_API_SUMMARY_PATH)%'
    tags: ['interfacing.query']
