framework:
  secret: 'interfacing-dev-secret'
  http_method_override: false
  handle_all_throwables: true
  php_errors:
    log: true
  session: true
  router:
    utf8: true
  validation:
    email_validation_mode: html5
  uid:
    default_uuid_version: 7
