# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
interfacing_layout_index:
  path: /interfacing
  controller: App\Interfacing\Presentation\Controller\Interfacing\LayoutController::show
  defaults:
    slug: home

interfacing_layout_show:
  path: /interfacing/{slug}
  controller: App\Interfacing\Presentation\Controller\Interfacing\LayoutController::show
  requirements:
    slug: '[a-z0-9][a-z0-9._-]{0,63}'
