# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
# Route ownership note:
# - Interfacing-owned controller routes are imported from config/routes/interfacing_attributes.yaml.
# - This file is intentionally kept as a legacy anchor for host applications that import
#   config/routes/interfacing.yaml directly, but it must not redeclare attribute-owned routes.
# - Do not add /interfacing/* catch-all routes here; keep broad routes after specific attributes.
