# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
# Canonical attribute route imports for Interfacing-owned controllers.
# Keep broad/catch-all controllers last so specific screen routes win first.


