services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Http\Interfacing\Health\Controller\InterfacingHealthController:
    arguments:
      $kernelEnvironment: '%kernel.environment%'
